# Generated by Django 3.2.7 on 2025-03-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20250320_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_password_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
